### ISSUE TITLE
Export BRRES - UV problem

### ISSUE THREAD

**Issue by Synell** [hayden0729/berrybush#10]
I'm using blender 3.3 LTS and berrybush 1.4.3

I have this penguin and tried to fixed his eyes as the uv was wrong.
![image](https://github.com/hayden0729/berrybush/assets/70210528/de9484fd-2954-4333-88cf-0eaba16e3cf5)

Inside berrybush, it looks right (image above), but when I export it, the uv is not applied to the new brres (image below).
When I tried to re-import the exported brres inside berrybush, the uv is the same as before the edits, so it didn't apply the changes.
![image](https://github.com/hayden0729/berrybush/assets/70210528/dfd13407-8b5d-48bb-a175-0f44a3f0be54)

When making the new uv, I did a new smart uv project (edit: does the same thing if executing unwrap instead of smart uv project):
![image](https://github.com/hayden0729/berrybush/assets/70210528/da9c5dd0-115f-4aa0-ad2f-85da7a33ed9f)

And moved/scaled it to fit the texture and I changed the coordinate source to UV2 (was UV1 before).
![image](https://github.com/hayden0729/berrybush/assets/70210528/3ae90fbe-a1c4-419e-9795-b80abb0d028d)

Maybe I'm just dumb and did something wrong, so here is the blend file if you want to look at it yourself: [untitled.zip](https://github.com/user-attachments/files/16039252/untitled.zip)

**Comment by hayden0729** [comment]
Thanks for the report! It looks like this was a bug caused by using UV slot 2 while slot 1 was unused (which is completely valid and should be supported - I just never realized it didn't actually work). 
![image](https://github.com/hayden0729/berrybush/assets/69529462/08ed5d8d-a85e-4138-adc4-3187ed274a6d)
Can you verify if [this new release](https://github.com/hayden0729/berrybush/releases/tag/1.4.4) fixes the issue?

**Comment by Synell** [comment]
It indeed fixed it, thank you !
